spring.application.name=ORDERSERVICE
server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.datasource.url=jdbc:mysql://localhost:3306/Team_DB
spring.datasource.username=root
spring.datasource.password=Tara1@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

##circuit breaker properties
##resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.slidingWindowSize=10
##resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.failureRateThreshold=50
##resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.waitDurationInOpenState=10s

feign.client.config.default.connectTimeout=2000
feign.client.config.default.readTimeout=2000
feign.client.config.default.decode404=false
spring.cloud.openfeign.retryer=none

resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.failure-rate-threshold=50 
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.wait-duration-in-open-state=10
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.register-health-indicator=true
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.sliding-window-type=count-based
##for actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

#for circuitbreaker andratelimmiter
management.health.circuitbreakers.enabled=true
management.health.ratelimiters.enabled=true